version: 2
jobs:
  build:
    docker:
      - image: python:3.7-alpine
    steps:
      - checkout
      - run: apk add --no-cache git
      - run: pip install tox~=3.7.0
      - restore_cache:
          key: >
            dependency-cache
            -{{ checksum "tox.ini" }}
            -{{ checksum "requirements.txt" }}
            -{{ checksum "test-requirements.txt" }}
      - run: tox --notest
      - save_cache:
          key: >
            dependency-cache
            -{{ checksum "tox.ini" }}
            -{{ checksum "requirements.txt" }}
            -{{ checksum "test-requirements.txt" }}
          paths:
            - .tox
      - run: tox -e coala -- --non-interactive
      - run: tox -e pylint
      - run: tox -e tests
